### ISSUE TITLE
Investigate circle-ci repository link in Cargo.toml

### ISSUE THREAD

**Issue by TimJentzsch** [DioxusLabs/stretch#18]
In [`Cargo.toml`](Cargo.toml), there is still a reference to the vislyhq/stretch repository for a `circle-ci` badge.

I'm not really sure what this means, but I assume it will have to either be removed or updated to point to DioxusLabs/stretch.

```toml
[badges]
circle-ci = { repository = "vislyhq/stretch", branch = "master" }
maintenance = { status = "experimental" }
```
